---
version: '3.8'

networks:
  system-integration:
    name: system-integration

services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.21.3
    container_name: 'weaviate'
    ports:
    - 8080:8080
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
        # AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'test-key'
      AUTHENTICATION_APIKEY_USERS: 'test'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'backup-filesystem'
      BACKUP_FILESYSTEM_PATH: '/'
      CLUSTER_HOSTNAME: 'weaviate1'
      LOG_LEVEL: 'debug'
    networks:
      - system-integration

  si-tests:
    image: alpine/curl:8.1.2
    container_name: 'si-tests'
    command: sleep infinity
    networks:
      - system-integration
...
