---
version: '3.8'

networks:
  cicd:
    name: cicd
  local:
    name: local

services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.21.3
    container_name: 'weaviate'
    ports:
    - 8080:8080
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
        # AUTHENTICATION_APIKEY_ENABLED: 'true'
        # AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'test-key'
        # AUTHENTICATION_APIKEY_USERS: 'test'
        # AUTHENTICATION_OIDC_ENABLED: 'true'
        # AUTHENTICATION_OIDC_ISSUER: 'https://auth.wcs.api.weaviate.io/auth/realms/SeMI'
        # AUTHENTICATION_OIDC_CLIENT_ID: 'wcs'
        # AUTHENTICATION_OIDC_USERNAME_CLAIM: 'email'
        # AUTHORIZATION_ADMINLIST_ENABLED: 'true'
        # AUTHORIZATION_ADMINLIST_USERS: 's.pewton@outlook.com'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'backup-filesystem'
      DEFAULT_VECTORIZER_MODULE: 'none'
      BACKUP_FILESYSTEM_PATH: '/'
      CLUSTER_HOSTNAME: 'weaviate1'
      LOG_LEVEL: 'debug'
    networks:
      - cicd

  weaviate-local:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.21.3
    container_name: 'weaviate'
    ports:
    - 8081:8081
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
        # AUTHENTICATION_APIKEY_ENABLED: 'true'
        # AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'test-key'
        # AUTHENTICATION_APIKEY_USERS: 'test'
        # AUTHENTICATION_OIDC_ENABLED: 'true'
        # AUTHENTICATION_OIDC_ISSUER: 'https://auth.wcs.api.weaviate.io/auth/realms/SeMI'
        # AUTHENTICATION_OIDC_CLIENT_ID: 'wcs'
        # AUTHENTICATION_OIDC_USERNAME_CLAIM: 'email'
        # AUTHORIZATION_ADMINLIST_ENABLED: 'true'
        # AUTHORIZATION_ADMINLIST_USERS: 's.pewton@outlook.com'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CONTEXTIONARY_URL: contextionary:9999
      ENABLE_MODULES: 'backup-filesystem,text2vec-contextionary'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-contextionary'
      BACKUP_FILESYSTEM_PATH: '/'
      CLUSTER_HOSTNAME: 'weaviate1'
      LOG_LEVEL: 'debug'
    networks:
      - local

  contextionary:
    container_name: 'text2vec-contextionary'
    environment:
      OCCURENCE_WEIGHT_LINEAR_FACTOR: 0.75
      EXTENSIONS_STORAGE_MODE: weaviate
      EXTENSIONS_STORAGE_ORIGIN: http://weaviate:8081
      NEIGHBOUR_OCCURRENCE_IGNORE_PERCENTILE: 5
      ENABLE_COMPOUND_SPLITTING: 'false'
    image: semitechnologies/contextionary:en0.16.0-v1.2.1
    ports:
      - 9999:9999
    networks:
      - local

  tests:
    image: rust:latest
    container_name: 'tests'
    command: 
      - /bin/sh 
      - -c 
      - | 
        cd /app/weaviate-community
        sleep infinity
    volumes:
      - ./weaviate-community:/app
    networks:
      - cicd
...
