---
version: 2.1
executors:
  my-executor:
    docker:
      - image: sampewton/circleci-base:latest
    resource_class: small

jobs:
  test:
    executor: my-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start compose
          command: |
            set -x
            docker-compose create weaviate tests && docker-compose start weaviate tests
      - run:
          name: See port bindings
          command: |
            docker ps
      - run:
          name: Run the --lib tests
          command: |
            docker exec -it tests sh -c "cd /app/weaviate-community && cargo test --lib"
      - run:
          name: Stop Docker compose
          command: |
            docker-compose down

  publish:
    executor: my-executor
    steps:
      - run:
          name: Placeholder
          command: |
            echo "This will publish the latest version to crates.io and tag the repo eventually"

workflows:
  version: 2
  weaviate-community:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only:
                - main
...
