---
version: 2.1
executors:
  my-executor:
    docker:
      - image: sampewton/circleci-base:latest
    resource_class: small

jobs:
  si-test:
    executor: my-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start compose
          command: |
            set -x
            docker-compose up -d
      - run:
          name: See port bindings
          command: |
            docker ps
      - run:
          name: Curl the meta endpoint
          command: |
            docker exec -it si-tests curl weaviate:8080/v1/meta
      - run:
          name: Stop Docker compose
          command: |
            docker-compose down
  publish:
    executor: my-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Placeholder
          command: |
            echo "This will publish the latest version to crates.io and tag the repo eventually"

workflows:
  version: 2
  weaviate-community:
    jobs:
      - si-test
      - publish:
          filters:
            branches:
              only:
                - main
...
