---
version: 2.1
executors:
  my-executor:
    docker:
      - image: sampewton/circleci-base:latest
    resource_class: small

jobs:
  setup:
    executor: my-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Start compose
          command: |
            set -x
            docker-compose create weaviate si-tests && docker-compose start weaviate si-tests
      - run:
          name: See port bindings
          command: |
            docker ps

  unit-test:
    executor: my-executor
    steps:
  si-test:
    executor: my-executor
    steps:
      - run:
          name: Curl the meta endpoint
          command: |
            docker exec -it tests 

  publish:
    executor: my-executor
    steps:
      - run:
          name: Placeholder
          command: |
            echo "This will publish the latest version to crates.io and tag the repo eventually"
      - run:
          name: Stop Docker compose
          command: |
            docker-compose down

workflows:
  version: 2
  weaviate-community:
    jobs:
      - setup
      - unit-test:
          requires:
            - setup
      - publish:
          requires:
            - si-test
          filters:
            branches:
              only:
                - main
...
