---
version: 2.1
  # executors:
  #   my-executor:
  #     docker:
  #       - image: cimg/base
  #         # - image: sampewton/circleci-base:latest
  #     resource_class: small

jobs:
  test:
    # executor: my-executor
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      # - run:
      #     name: Start compose
      #     command: |
      #       set -x
      #       docker-compose create weaviate tests && docker-compose start weaviate tests
      # - run:
      #     name: Add project to test container
      #     command: |
      #       docker cp ./weaviate-community tests:/weaviate-community
      # - run:
      #     name: See port bindings
      #     command: |
      #       docker ps
      # - run:
      #     name: Run the --lib tests
      #     command: |
      #       docker exec -it tests sh -c "cd /weaviate-community && cargo test --lib"
      # - run:
      #     name: Run the --doc tests
      #     command: |
      #       docker exec -it tests sh -c "cd /weaviate-community && cargo test --doc"
      # - run:
      #     name: Run the SI tests (when running on master branch)
      #     command: |
      #       echo TODO
      # - run:
      #     name: Stop Docker compose
      #     command: |
      #       docker-compose down

  publish:
    # executor: my-executor
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Show current tag
          command: |
            echo "export CURRENT_GIT_TAG=git describe --tags | sed 's/v//'" >> "$BASH_ENV"
      - run:
          name: Show crates.io version
          command: |
            echo "export CARGO_TOML_VERSION=cat ./weaviate-community/Cargo.toml | grep 'version = ' | head -1 | awk '{ print $3 }' | sed 's/\"//g'" >> "$BASH_ENV"
      - run:
          name: Check version
          command: |
            echo $CURRENT_GIT_TAG

workflows:
  version: 2
  weaviate-community:
    jobs:
      - test
      - publish:
          requires:
            - test
              # filters:
              #   branches:
              #     only:
              #       - main
...
